[package]
name = "stm32f1_blinky"
version = "0.1.0"
authors = ["KONDO Nobuhiro <kondou.nobuhiro@gmail.com>"]
build = "build.rs"

[dependencies]
stm32cubef1 = {path = "../stm32cubef1"}

[build-dependencies]
